// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "contests" => http://localhost:9033/admin/info/contests
// "submissions" => http://localhost:9033/admin/info/submissions
// "users" => http://localhost:9033/admin/info/users
// "users_in_groups" => http://localhost:9033/admin/info/users_in_groups
// "groups" => http://localhost:9033/admin/info/groups
// "tasks" => http://localhost:9033/admin/info/tasks
//
// example end
var Generators = map[string]table.Generator{

	"contests":        GetContestsTable,
	"submissions":     GetSubmissionsTable,
	"users":           GetUsersTable,
	"users_in_groups": GetUsersingroupsTable,
	"groups":          GetGroupsTable,
	"tasks":           GetTasksTable,

	// generators end
}
